// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDILyJLTxwOlNjRSLKIA3xJT1sX4JbrXfs',
    appId: '1:260712036852:web:00b943a3923a536c62e1a1',
    messagingSenderId: '260712036852',
    projectId: 'fruit-fresh-8ca3e',
    authDomain: 'fruit-fresh-8ca3e.firebaseapp.com',
    storageBucket: 'fruit-fresh-8ca3e.firebasestorage.app',
    measurementId: 'G-W3HMSVSE2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJC3KliTPr_ooWRCXLNVtPSqWDpm8jJr4',
    appId: '1:260712036852:android:f65a57064832e50662e1a1',
    messagingSenderId: '260712036852',
    projectId: 'fruit-fresh-8ca3e',
    storageBucket: 'fruit-fresh-8ca3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqvk8_la40_AuVoTQThRq6XDVcfOgv0oQ',
    appId: '1:260712036852:ios:a9a78e0bce3886a062e1a1',
    messagingSenderId: '260712036852',
    projectId: 'fruit-fresh-8ca3e',
    storageBucket: 'fruit-fresh-8ca3e.firebasestorage.app',
    iosClientId: '260712036852-04ik738s1rvrd7a8b0hku8r9psftt1eg.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodPrediction',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqvk8_la40_AuVoTQThRq6XDVcfOgv0oQ',
    appId: '1:260712036852:ios:a9a78e0bce3886a062e1a1',
    messagingSenderId: '260712036852',
    projectId: 'fruit-fresh-8ca3e',
    storageBucket: 'fruit-fresh-8ca3e.firebasestorage.app',
    iosClientId: '260712036852-04ik738s1rvrd7a8b0hku8r9psftt1eg.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodPrediction',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDILyJLTxwOlNjRSLKIA3xJT1sX4JbrXfs',
    appId: '1:260712036852:web:c938bd62bab76cea62e1a1',
    messagingSenderId: '260712036852',
    projectId: 'fruit-fresh-8ca3e',
    authDomain: 'fruit-fresh-8ca3e.firebaseapp.com',
    storageBucket: 'fruit-fresh-8ca3e.firebasestorage.app',
    measurementId: 'G-QGVQ2C3302',
  );

}